# Generated by Django 4.2 on 2023-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("warmupper", "warmupper"),
                    ("manager", "manager"),
                    ("admin", "admin"),
                    ("sender", "sender"),
                ],
                default="admin",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
