# Generated by Django 4.2 on 2023-05-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="privilege",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "bronze"), (2, "silver"), (3, "gold")],
                null=True,
            ),
        ),
    ]
