# Generated by Django 4.2.1 on 2023-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_privilege"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("warmupper", "warmupper"),
                    ("manager", "manager"),
                    ("admin", "admin"),
                    ("sender", "sender"),
                    ("director", "director"),
                ],
                max_length=20,
            ),
        ),
    ]
