# Generated by Django 4.2 on 2023-05-07 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("senders", "0006_alter_emaillist_gmail_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="managerActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "todo"),
                            ("in_progress", "in_progress"),
                            ("done", "done"),
                            ("rejected", "rejected"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "action_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_details",
                        to="senders.emaillist",
                    ),
                ),
            ],
        ),
    ]
