# Generated by Django 4.2 on 2023-05-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0002_alter_manageractions_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageractions",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "todo"),
                    ("in_progress", "in_progress"),
                    ("done", "done"),
                    ("rejected", "rejected"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
