# Generated by Django 4.2.1 on 2023-05-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0011_emaillistrequest_remove_emaillist_sender"),
        ("managers", "0006_rename_action_manageractions_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageractions",
            name="action_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_details",
                to="senders.emaillistrequest",
            ),
        ),
    ]
