# Generated by Django 4.2 on 2023-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warmuppers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddress",
            name="email",
            field=models.EmailField(
                default="jon@gmail.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
