# Generated by Django 4.2 on 2023-05-03 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warmuppers", "0003_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_assignments",
                to="warmuppers.emailaddress",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_senders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="warmupper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_warmuppers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
