# Generated by Django 4.2 on 2023-05-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warmuppers", "0004_alter_assignment_email_alter_assignment_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaddress",
            name="mailbox_provider",
            field=models.CharField(
                choices=[
                    ("gmail", "gmail"),
                    ("google_workspace", "google_workspace"),
                    ("microsoft", "microsoft"),
                    ("msft_365", "msft_365"),
                    ("yahoo", "yahoo"),
                    ("other", "other"),
                ],
                max_length=20,
            ),
        ),
    ]
