# Generated by Django 4.2 on 2023-05-19 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warmuppers", "0006_emailaddressassignment_delete_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAddressEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "datatype",
                    models.CharField(
                        choices=[("opens", "opens"), ("clicks", "clicks")],
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_emails",
                        to="warmuppers.emailaddress",
                    ),
                ),
                (
                    "warmupper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_warmuppers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
