# Generated by Django 4.2 on 2023-05-19 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warmuppers", "0008_alter_emailaddressengagement_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaddressengagement",
            name="warmupper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagement_warmuppers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
