# Generated by Django 4.2.1 on 2023-05-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warmuppers", "0009_alter_emailaddressengagement_warmupper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailaddressengagement",
            name="datatype",
        ),
        migrations.AddField(
            model_name="emailaddressengagement",
            name="data_type",
            field=models.CharField(
                choices=[("open", "opens"), ("click", "clicks")],
                default="open",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
