# Generated by Django 4.2 on 2023-05-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("gmail_count", models.PositiveSmallIntegerField(default=0)),
                ("microsoft_count", models.PositiveSmallIntegerField(default=0)),
                ("yahoo_count", models.PositiveSmallIntegerField(default=0)),
                ("other_count", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
