# Generated by Django 4.2 on 2023-05-03 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("senders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillist",
            name="name",
            field=models.CharField(default="trololo", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaillist",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_emaillists",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
