# Generated by Django 4.2 on 2023-05-04 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0002_emaillist_name_emaillist_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillist",
            name="gmail_count",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="emaillist",
            name="microsoft_count",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="emaillist",
            name="other_count",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="emaillist",
            name="yahoo_count",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(2)]
            ),
        ),
    ]
