# Generated by Django 4.2 on 2023-05-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0006_alter_emaillist_gmail_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillist",
            name="google_workspace_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emaillist",
            name="msft_365_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
