# Generated by Django 4.2 on 2023-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0007_emaillist_google_workspace_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillist",
            name="sender_addresses",
            field=models.CharField(
                default="offers@email.cocacola.com", max_length=1000
            ),
            preserve_default=False,
        ),
    ]
