# Generated by Django 4.2 on 2023-05-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0008_emaillist_sender_addresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillist",
            name="sender_addresses",
            field=models.CharField(
                help_text="Separate multiple sender addresses with semi-colons.",
                max_length=1000,
            ),
        ),
    ]
