# Generated by Django 4.2.1 on 2023-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0010_alter_emaillist_sender_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailListRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("sender_addresses", models.CharField(max_length=1000)),
                ("gmail_count", models.PositiveSmallIntegerField(default=0)),
                ("google_workspace_count", models.PositiveSmallIntegerField(default=0)),
                ("microsoft_count", models.PositiveSmallIntegerField(default=0)),
                ("msft_365_count", models.PositiveSmallIntegerField(default=0)),
                ("yahoo_count", models.PositiveSmallIntegerField(default=0)),
                ("other_count", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="emaillist",
            name="sender",
        ),
    ]
