# Generated by Django 4.2.1 on 2023-05-25 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0011_emaillistrequest_remove_emaillist_sender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("managers", "0007_alter_manageractions_action_details"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailList",
        ),
        migrations.AddField(
            model_name="emaillistrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_emaillist_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
