# Generated by Django 4.2.1 on 2023-05-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warmuppers", "0010_remove_emailaddressengagement_datatype_and_more"),
        ("senders", "0012_delete_emaillist_emaillistrequest_sender"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailListAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_list_assignments",
                        to="warmuppers.emailaddress",
                    ),
                ),
                (
                    "email_list_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_list_assignments",
                        to="senders.emaillistrequest",
                    ),
                ),
            ],
        ),
    ]
